### ISSUE TITLE
Crear semilla de datos para usuarios y login

### ISSUE THREAD

**Issue by allamasln** [TheBridge-FullStackDeveloper/ft-feb13-team#9]
Documentarla en un JSON para que la tenga todo el equipo

**Comment by DaniFunes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Crear semilla de datos para usuarios y login](https://trello.com/c/gcg2K66M/39-crear-semilla-de-datos-para-usuarios-y-login)
